
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from yacs.config import CfgNode as CN
_C = CN()

_C.KEYPOINT_FILE = ""
_C.TRAIN_TEST_SPLIT = ""
_C.CROP_IMAGE = ""
_C.CLIP_LENGTH = 8
_C.OUT_DIR = r"out"
_C.TRAIN_INITIAL_WEIGHT = ""
_C.TEST_INITIAL_WEIGHT = ""
_C.FORMAT_DATASET = True
_C.DATASET_PATH = r"D:\pose\pain\data\pain_data"
_C.CHECKPOINTS_FOLD = "checkpoints"
_C.NUM_GPUS = 1

_C.MODEL = CN()
_C.MODEL.MODEL_NAME = "two_lstm"
_C.MODEL.NUM_CLSTM_LAYERS = 4
_C.MODEL.CLSTM_HIDDEN_SIZE = 32
_C.MODEL.LSTM_HIDDEN_SIZE = 32
_C.MODEL.NUM_LSTM_LAYERS = 4
_C.MODEL.LSTM_INPUT_SIZE = 34
_C.MODEL.IMG_SIZE = (224, 224)
_C.MODEL.NUM_LABELS = 2

_C.SOLVER = CN()
_C.SOLVER.METHOD = "sgd"
_C.SOLVER.BASE_LR = 0.1
_C.SOLVER.MOMENTUM = 0.9
_C.SOLVER.WEIGHT_DECAY = 1e-4
_C.SOLVER.DAMPENING = 0.0
_C.SOLVER.NESTEROV = True
_C.SOLVER.WARMUP_EPOCHS = 20
_C.SOLVER.WARMUP_START_LR = 0.01
_C.SOLVER.COSINE_AFTER_WARMUP = False
_C.SOLVER.COSINE_END_LR = 0.0
_C.SOLVER.MAX_EPOCH = 100
_C.ENABLE_VAL = False

_C.RUN = CN()
_C.RUN.TEST_BATCH_SIZE = 1
_C.RUN.TRAIN_BATCH_SIZE = 16
_C.RUN.NUM_WORKS = 2
_C.RUN.AUTO_RESUME = True